# -*- coding: utf-8 -*-
"""TASK 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1na0waUeB8vRPgdk44hAtzoZE6pITxo4u
"""

# Courtesy: Michael Beyeler
#  How to create a beautiful pencil sketch effect with OpenCV and Python  https://www.askaswiss.com/2016/01/how-to-create-pencil-sketch-opencv-python.htm

from google.colab.patches import cv2_imshow

import cv2

img = cv2.imread("/content/_DSC2755.JPG")

cv2_imshow(img)

img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2_imshow(img_gray)

img_invert = cv2.bitwise_not(img_gray)

cv2_imshow(img_invert)

img_smoothing = cv2.GaussianBlur(img_invert, (21, 21),sigmaX=0, sigmaY=0)

cv2_imshow(img_smoothing)

def dodgeV2(x, y):
    return cv2.divide(x, 255 - y, scale=256)

final_img = dodgeV2(img_gray, img_smoothing)

cv2_imshow(final_img)